export const KnownStatusCodes = [
    { code: 100, description: "Continue" },
    { code: 101, description: "Switching Protocols" },
    { code: 102, description: "Processing" },
    { code: 200, description: "OK" },
    { code: 201, description: "Created" },
    { code: 202, description: "Accepted" },
    { code: 203, description: "Non-Authoritative Information" },
    { code: 204, description: "No Content" },
    { code: 205, description: "Reset Content" },
    { code: 206, description: "Partial Content" },
    { code: 207, description: "Multi-Status" },
    { code: 226, description: "IM Used" },
    { code: 300, description: "Multiple Choices" },
    { code: 301, description: "Moved Permanently" },
    { code: 302, description: "Moved Temporarily" },
    { code: 303, description: "See Other" },
    { code: 304, description: "Not Modified" },
    { code: 305, description: "Use Proxy" },
    { code: 307, description: "Temporary Redirect" },
    { code: 400, description: "Bad Request" },
    { code: 401, description: "Unauthorized" },
    { code: 402, description: "Payment Required" },
    { code: 403, description: "Forbidden" },
    { code: 404, description: "Not Found" },
    { code: 405, description: "Method Not Allowed" },
    { code: 406, description: "Not Acceptable" },
    { code: 407, description: "Proxy Authentication Required" },
    { code: 408, description: "Request Timeout" },
    { code: 409, description: "Conflict" },
    { code: 410, description: "Gone" },
    { code: 411, description: "Length Required" },
    { code: 412, description: "Precondition Failed" },
    { code: 413, description: "Request Entity Too Large" },
    { code: 414, description: "Request-URI Too Large" },
    { code: 415, description: "Unsupported Media Type" },
    { code: 416, description: "Requested Range Not Satisfiable" },
    { code: 417, description: "Expectation Failed" },
    { code: 422, description: "Unprocessable Entity" },
    { code: 423, description: "Locked" },
    { code: 424, description: "Failed Dependency" },
    { code: 425, description: "Unordered Collection" },
    { code: 426, description: "Upgrade Required" },
    { code: 429, description: "Too many requests" },
    { code: 449, description: "Retry With" },
    { code: 456, description: "Unrecoverable Error" },
    { code: 500, description: "Internal Server Error" },
    { code: 501, description: "Not Implemented" },
    { code: 502, description: "Bad Gateway" },
    { code: 503, description: "Service Unavailable" },
    { code: 504, description: "Gateway Timeout" },
    { code: 505, description: "HTTP Version Not Supported" },
    { code: 506, description: "Variant Also Negotiates" },
    { code: 507, description: "Insufficient Storage" },
    { code: 508, description: "Loop Detected" },
    { code: 509, description: "Bandwidth Limit Exceeded" },
    { code: 510, description: "Not Extended" }
];