name: Fetch Open Issues

on:
  workflow_dispatch:

jobs:
  fetch-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch open issues
        id: issues
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/Azure/api-management-developer-portal/issues?state=open
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBACTIONS_TOKEN }}

      - name: Print issue URLs
        run: |
          const issues = JSON.parse('${{ steps.issues.outputs.data }}');
          const filteredIssues = issues.filter(issue => issue.body.includes('Is your portal managed or self-hosted?\r\n\r\nManaged'));
          for (const issue of filteredIssues) {
            console.log(issue.html_url);
          }
        shell: node
