name: CI
on:
  push:
    branches: [ release/** ]
  pull_request:
    branches: [ develop, master ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout
        
      - run: npm install
        name: Npm install
                
      - uses: cschleiden/replace-tokens@v1
        name: Replace token
        env:
          AZURE_APIM_DEVELOPER_PORTAL_URL: ${{ secrets.AZURE_APIM_DEVELOPER_PORTAL_URL }}
          AZURE_APIM_ID: ${{ secrets.AZURE_APIM_ID }}
          AZURE_APIM_MANAGEMENT_SAS_ACCESS_TOKEN:  ${{ secrets.AZURE_APIM_MANAGEMENT_SAS_ACCESS_TOKEN }}
          AZURE_APIM_MANAGEMENT_URL:  ${{ secrets.AZURE_APIM_MANAGEMENT_URL }}
          AZURE_STORAGE_SAS_URL: ${{ secrets.AZURE_STORAGE_SAS_URL }}
        with:
          files: '["**/config.*.json"]'
      
      - run: npm run publish
        name: Publish
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with: 
          path: dist/website
        
  dev:
    name: Dev
    needs: build
    # if: github.head_ref == 'develop'
    environment: dev
    runs-on: ubuntu-latest
        
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2.0.8
    
      - name: Deploy to Azure Storage
        uses: TravisSpomer/deploy-to-azure-storage@v1.3.0
        with:
          source-path: dist/website
          sas-url: ${{ secrets.AZURE_STORAGE_SAS_URL }}
          
  uat:
    name: Uat
    needs: [build, dev]
    environment: uat
    runs-on: ubuntu-latest
        
    steps:
      - name: Deploy to Azure Storage
        uses: TravisSpomer/deploy-to-azure-storage@v1.3.0
        with:
          source-path: dist/website
          sas-url: ${{ secrets.AZURE_STORAGE_SAS_URL }}
          
  sdx:
    name: Sdx
    needs: build
    if: github.head_ref == 'release/**'
    environment: sdx
    runs-on: ubuntu-latest
        
    steps:
      - name: Deploy to Azure Storage
        uses: TravisSpomer/deploy-to-azure-storage@v1.3.0
        with:
          source-path: dist/website
          sas-url: ${{ secrets.AZURE_STORAGE_SAS_URL }}
          
  prd:
    name: Prd
    needs: build
    if: github.head_ref == 'master/**'
    environment: prd
    runs-on: ubuntu-latest
        
    steps:
      - name: Deploy to Azure Storage
        uses: TravisSpomer/deploy-to-azure-storage@v1.3.0
        with:
          source-path: dist/website
          sas-url: ${{ secrets.AZURE_STORAGE_SAS_URL }}
