name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - run: npm install
                
      - uses: cschleiden/replace-tokens@v1
        name: Replace token
        env:
          AZURE_APIM_DEVELOPER_PORTAL_URL: ${{ secrets.AZURE_APIM_DEVELOPER_PORTAL_URL }}
          AZURE_APIM_ID: ${{ secrets.AZURE_APIM_ID }}
          AZURE_APIM_MANAGEMENT_SAS_ACCESS_TOKEN:  ${{ secrets.AZURE_APIM_MANAGEMENT_SAS_ACCESS_TOKEN }}
          AZURE_APIM_MANAGEMENT_URL:  ${{ secrets.AZURE_APIM_MANAGEMENT_URL }}
          AZURE_STORAGE_SAS_URL: ${{ secrets.AZURE_STORAGE_SAS_URL }}
        with:
          files: '["**/config.*.json"]'
      
      - run: npm run publish
        
      - name: Deploy to Azure Storage
        uses: TravisSpomer/deploy-to-azure-storage@v1.3.0
        with:
          source-path: dist/website
          sas-url: ${{ secrets.AZURE_STORAGE_SAS_URL }}
